name: Update Weather

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  get-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Weather from API
        run: |
          CITY="Rupnagar,Punjab,IN"
          RESPONSE=$(curl "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=${{ secrets.WEATHER_API_KEY }}&units=metric")

          TEMP=$(echo $RESPONSE | jq '.main.temp')
          FEELS=$(echo $RESPONSE | jq '.main.feels_like')
          HUMID=$(echo $RESPONSE | jq '.main.humidity')
          WIND=$(echo $RESPONSE | jq '.wind.speed')
          CONDITION=$(echo $RESPONSE | jq -r '.weather[0].main')
          CITYNAME=$(echo $RESPONSE | jq -r '.name')

          echo "{
            \"temp\": $TEMP,
            \"feels_like\": $FEELS,
            \"humidity\": $HUMID,
            \"wind\": $WIND,
            \"condition\": \"$CONDITION\",
            \"city\": \"$CITYNAME\"
          }" > weather.json

      - name: Commit updated weather.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add weather.json
          git commit -m "Updated weather" || echo "No changes"
          git push
